"""empty message

Revision ID: 194befb66d6f
Revises: 1472c09a5f30
Create Date: 2020-01-05 06:05:28.375589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194befb66d6f'
down_revision = '1472c09a5f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentsignup', sa.Column('Contact', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentsignup', 'Contact')
    # ### end Alembic commands ###
