"""empty message

Revision ID: 1e948b879f1a
Revises: 5b3b17e40cc3
Create Date: 2020-01-06 09:14:02.289592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e948b879f1a'
down_revision = '5b3b17e40cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentsignup', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentsignup', 'is_admin')
    # ### end Alembic commands ###
