"""empty message

Revision ID: 319f70f8021f
Revises: f9828977997f
Create Date: 2020-01-04 07:21:29.387853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319f70f8021f'
down_revision = 'f9828977997f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulesignup', sa.Column('DateandTime', sa.DateTime(), nullable=True))
    op.add_column('schedulesignup', sa.Column('Day', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedulesignup', 'Day')
    op.drop_column('schedulesignup', 'DateandTime')
    # ### end Alembic commands ###
