"""empty message

Revision ID: 5b3b17e40cc3
Revises: 517c1cfbc3af
Create Date: 2020-01-06 05:09:48.424244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3b17e40cc3'
down_revision = '517c1cfbc3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentsignup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Firstname', sa.String(length=120), nullable=True),
    sa.Column('Lastname', sa.String(length=120), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Password', sa.String(length=120), nullable=True),
    sa.Column('Contact', sa.String(length=11), nullable=True),
    sa.Column('School', sa.String(length=120), nullable=True),
    sa.Column('Classification', sa.String(length=120), nullable=True),
    sa.Column('Major', sa.String(length=120), nullable=True),
    sa.Column('Gender', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('tutorsignup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Firstname', sa.String(length=120), nullable=True),
    sa.Column('Lastname', sa.String(length=120), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Password', sa.String(length=120), nullable=True),
    sa.Column('Contact', sa.Integer(), nullable=True),
    sa.Column('School', sa.String(length=120), nullable=True),
    sa.Column('Classification', sa.String(length=120), nullable=True),
    sa.Column('Major', sa.String(length=120), nullable=True),
    sa.Column('Gender', sa.String(length=120), nullable=True),
    sa.Column('Resume', sa.LargeBinary(), nullable=True),
    sa.Column('Transcript', sa.LargeBinary(), nullable=True),
    sa.Column('Classes', sa.String(length=120), nullable=True),
    sa.Column('Experience', sa.String(length=120), nullable=True),
    sa.Column('Expertise', sa.String(length=120), nullable=True),
    sa.Column('Reason', sa.String(length=120), nullable=True),
    sa.Column('Restriction', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('schedulesignup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Preferedname', sa.String(length=120), nullable=True),
    sa.Column('Classes', sa.String(length=120), nullable=True),
    sa.Column('Day', sa.String(length=120), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Time', sa.Time(), nullable=True),
    sa.Column('Taken', sa.String(length=120), nullable=True),
    sa.Column('Areas', sa.String(length=120), nullable=True),
    sa.Column('Comment', sa.String(length=120), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['studentsignup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedulesignup_timestamp'), 'schedulesignup', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedulesignup_timestamp'), table_name='schedulesignup')
    op.drop_table('schedulesignup')
    op.drop_table('tutorsignup')
    op.drop_table('studentsignup')
    # ### end Alembic commands ###
