"""empty message

Revision ID: 6bf71540a8a6
Revises: 78fbd6ea7e77
Create Date: 2019-12-25 08:05:11.675253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf71540a8a6'
down_revision = '78fbd6ea7e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorsignup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Firstname', sa.String(length=120), nullable=True),
    sa.Column('Lastname', sa.String(length=120), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Password', sa.String(length=120), nullable=True),
    sa.Column('Contact', sa.Integer(), nullable=True),
    sa.Column('School', sa.String(length=120), nullable=True),
    sa.Column('Classification', sa.String(length=120), nullable=True),
    sa.Column('Major', sa.String(length=120), nullable=True),
    sa.Column('Gender', sa.String(length=120), nullable=True),
    sa.Column('Resume', sa.LargeBinary(), nullable=True),
    sa.Column('Transcript', sa.LargeBinary(), nullable=True),
    sa.Column('Classes', sa.String(length=120), nullable=True),
    sa.Column('Experience', sa.String(length=120), nullable=True),
    sa.Column('Expertise', sa.String(length=120), nullable=True),
    sa.Column('Reason', sa.String(length=120), nullable=True),
    sa.Column('Restriction', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorsignup')
    # ### end Alembic commands ###
