"""empty message

Revision ID: 7563948b916c
Revises: 869ba77d78a2
Create Date: 2020-01-05 05:48:08.179468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7563948b916c'
down_revision = '869ba77d78a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentsignup', 'Firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentsignup', sa.Column('Firstname', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
