"""empty message

Revision ID: 869ba77d78a2
Revises: c269a0e7f3d9
Create Date: 2020-01-05 05:29:30.662181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869ba77d78a2'
down_revision = 'c269a0e7f3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulesignup', sa.Column('data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedulesignup', 'studentsignup', ['data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedulesignup', type_='foreignkey')
    op.drop_column('schedulesignup', 'data_id')
    # ### end Alembic commands ###
