"""empty message

Revision ID: c269a0e7f3d9
Revises: 319f70f8021f
Create Date: 2020-01-04 08:16:06.806657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c269a0e7f3d9'
down_revision = '319f70f8021f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulesignup', sa.Column('Date', sa.Date(), nullable=True))
    op.add_column('schedulesignup', sa.Column('Time', sa.Time(), nullable=True))
    op.drop_column('schedulesignup', 'DateandTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulesignup', sa.Column('DateandTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('schedulesignup', 'Time')
    op.drop_column('schedulesignup', 'Date')
    # ### end Alembic commands ###
