"""empty message

Revision ID: f9828977997f
Revises: febc4ed44f31
Create Date: 2019-12-31 03:33:32.602741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9828977997f'
down_revision = 'febc4ed44f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulesignup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Preferedname', sa.String(length=120), nullable=True),
    sa.Column('Classes', sa.String(length=120), nullable=True),
    sa.Column('Taken', sa.String(length=120), nullable=True),
    sa.Column('Areas', sa.String(length=120), nullable=True),
    sa.Column('Comment', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Preferedname', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('Classes', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('Taken', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('Areas', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('Comment', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='student_data_pkey')
    )
    op.drop_table('schedulesignup')
    # ### end Alembic commands ###
